/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 -s clog.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/clog.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.51, -0.195, -0.021]} scale={0.001}>
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��'].geometry} material={materials['재질_1.002']} position={[-553.931, 215.455, 57.552]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_10'].geometry} material={materials['재질_1.002']} position={[-505.897, 189.699, 100.8]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_11'].geometry} material={materials['재질_1.002']} position={[-508.633, 217.022, 10.933]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_2'].geometry} material={materials['재질_1.002']} position={[-468.531, 213.177, 57.971]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_3'].geometry} material={materials['재질_1.002']} position={[-468.453, 213.404, 59.558]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_4'].geometry} material={materials['재질_1.002']} position={[-468.486, 213.587, 58.868]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_5'].geometry} material={materials['재질_1.002']} position={[-468.721, 214.881, 56.701]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_6'].geometry} material={materials['재질_1.002']} position={[-467.654, 211.072, 41.304]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_7'].geometry} material={materials['재질_1.002']} position={[-467.738, 213.7, 41.262]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_8'].geometry} material={materials['재질_1.002']} position={[-468.01, 222.304, 41.088]} />
        <mesh castShadow receiveShadow geometry={nodes['COLOR=�,MATERIAL=��_9'].geometry} material={materials['재질_1.002']} position={[-468.24, 212.7, 62.247]} />
      </group>
    </group>
  )
}

useGLTF.preload('/clog.glb')
